import logging
from dataclasses import fields
from pathlib import Path

import yaml

from ..profiles import load_profile
from .schema import (
    AnalysisConfig,
    CaptureConfig,
    CLAPSourceConfig,
    LibrarySourceConfig,
    OutputConfig,
    RunConfig,
    VSTSourceConfig,
    WavetableConfig,
    WavetableSourceConfig,
)

log = logging.getLogger(__name__)

_TOP_LEVEL_KEYS = {"source", "capture", "analysis", "output", "profile", "name", "category", "wavetable"}


def _warn_unknown(section_name: str, section: dict, allowed: set[str], path: Path) -> None:
    """Warn about YAML keys that no dataclass field will consume.

    Silent drop-on-typo is a common footgun (see `loop_qulity_threshold` etc.):
    the loader falls back to defaults with no signal. This is a WARN, not a raise,
    because CLAUDE.md treats YAMLs as the escape hatch for hand-edits and users may
    legitimately annotate configs with unrecognized keys.
    """
    if not isinstance(section, dict):
        return
    unknown = set(section) - allowed
    if unknown:
        log.warning(
            "%s: unknown key(s) in `%s`: %s (dropped — typo? or documented?)",
            path, section_name, sorted(unknown),
        )


def _deep_merge(base: dict, override: dict) -> dict:
    merged = dict(base)
    for k, v in override.items():
        if k in merged and isinstance(merged[k], dict) and isinstance(v, dict):
            merged[k] = _deep_merge(merged[k], v)
        else:
            merged[k] = v
    return merged


def load_config(path: Path) -> RunConfig:
    raw = yaml.safe_load(path.read_text())

    if "profile" in raw:
        base = load_profile(raw["profile"])
        raw = _deep_merge(base, raw)

    _warn_unknown("<top level>", raw, _TOP_LEVEL_KEYS, path)
    _warn_unknown("capture", raw.get("capture", {}), {f.name for f in fields(CaptureConfig)}, path)
    _warn_unknown("analysis", raw.get("analysis", {}), {f.name for f in fields(AnalysisConfig)}, path)
    _warn_unknown("output", raw.get("output", {}), {f.name for f in fields(OutputConfig)}, path)

    # Anchor relative paths on the config file's parent directory so a config
    # generated by a scan command with a relative CLI arg (e.g. `assemble-kits
    # ./library ./configs/`) still resolves correctly when `sample`/`batch` is
    # later invoked from a different cwd. Absolute paths are left as-is.
    config_dir = path.parent

    def _abspath(s: str) -> Path:
        p = Path(s)
        return p if p.is_absolute() else (config_dir / p).resolve()

    src = raw["source"]
    if src["type"] == "vst":
        source = VSTSourceConfig(
            plugin=_abspath(src["plugin"]),
            preset=src.get("preset"),
            raw_state=src.get("raw_state"),
        )
    elif src["type"] == "clap":
        source = CLAPSourceConfig(
            plugin=_abspath(src["plugin"]),
            plugin_id=src["plugin_id"],
            preset=src.get("preset"),
            preset_path=_abspath(src["preset_path"]) if src.get("preset_path") else None,
            raw_state=src.get("raw_state"),
        )
    elif src["type"] == "library":
        source = LibrarySourceConfig(
            path=_abspath(src["path"]),
            filename_pattern=src.get("filename_pattern"),
            note=src.get("note"),
            drumkit=src.get("drumkit", False),
            files=[_abspath(p) for p in src["files"]] if "files" in src else None,
        )
    elif src["type"] == "wavetable":
        source = WavetableSourceConfig(path=_abspath(src["path"]))
    else:
        raise ValueError(f"Unknown source type: {src['type']!r}")

    cap = raw.get("capture", {})
    capture = CaptureConfig(
        note_range=tuple(cap.get("note_range", [36, 96])),
        note_step=cap.get("note_step", 3),
        velocities=cap.get("velocities", [100]),
        round_robins=cap.get("round_robins", 1),
        duration_s=cap.get("duration_s", 4.0),
        release_tail_s=cap.get("release_tail_s", 2.0),
        tempo_bpm=cap.get("tempo_bpm", 120.0),
        sample_rate=cap.get("sample_rate", 48000),
    )

    ana = raw.get("analysis", {})
    analysis = AnalysisConfig(
        trim=ana.get("trim", True),
        pitch_verify=ana.get("pitch_verify", True),
        pitch_tolerance_cents=ana.get("pitch_tolerance_cents", 50.0),
        loop=ana.get("loop", False),
        loop_use_tempo=ana.get("loop_use_tempo", False),
        loop_quality_threshold=ana.get("loop_quality_threshold", 0.8),
        loop_crossfade_ms=ana.get("loop_crossfade_ms", 10.0),
        tempo_bpm=ana.get("tempo_bpm"),
        normalize=ana.get("normalize", "per_set"),
        classify_drums=ana.get("classify_drums", False),
    )

    out = raw["output"]
    output = OutputConfig(
        name=out["name"],
        subfolder=out.get("subfolder", ""),
    )

    wt = raw.get("wavetable")
    wavetable = (
        WavetableConfig(
            archetype=wt["archetype"],
            wt_position=wt["wt_position"],
            lfo2_rate=wt["lfo2_rate"],
            lfo2_depth=wt["lfo2_depth"],
            filter_cutoff=wt["filter_cutoff"],
            attack=wt["attack"],
            decay=wt["decay"],
            sustain=wt["sustain"],
            release=wt["release"],
            filter_type=wt.get("filter_type", "lpf"),
        )
        if wt is not None
        else None
    )

    return RunConfig(
        source=source,
        capture=capture,
        analysis=analysis,
        output=output,
        name=raw.get("name", output.name),
        category=raw.get("category", "synth"),
        wavetable=wavetable,
    )
